### ISSUE TITLE
The link for an example isn't highlighted

### ISSUE THREAD

**Issue by Lextuga007** [matt-dray/govspeakify-tables#10]
I missed this [Click here for an example table to copy.](https://github.com/matt-dray/govspeakify-tables/blob/023e9ddb4fb62b8aaeab1881c31e707759737e5b/govspeakify-tables/app.R#L18) in the app as the highlight isn't working for this link (but does for the others). I noticed you gave a table to copy when I looked at the code 😄

**Comment by matt-dray** [comment]
Aha, rather than a hyperlink, there should be a little 'triangle' dropdown marker for [the expandable `<details>` block](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) (visible in the gif in the README). But I've noticed it doesn't appear in certain browsers for some reason (e.g. not showing for me in Chrome on Windows 10).

Two ideas:

1. Work out why the little triangle doesn't appear and fix it (I use details blocks in blog posts and I don't think it's been a problem there, so maybe it's related to how I've written the HTML inside this Shiny app, specifically).
2. Imply the block is expandable using an emoji or icon or something.

**Comment by Lextuga007** [comment]
Oh I see! I've used the triangle in Quarto chunks before and now it makes sense why the whole sentence is a link. 

I'm using Edge.

I'd go for option 2 but option 1 will possibly lead to a deeper understanding of html in shiny! 😄

**Comment by matt-dray** [comment]
For my own reference, might need to do this: https://github.com/rstudio/rmarkdown/issues/1483

``` css
summary {
  display: list-item
}
```

Edit: yep, that worked.
